@startuml
class Usuario {
  - nombre: String
  - direccion: String
  - correoElectronico: String
  - idUsuario: int
  - contrasena: String
  + registrar(): void
  + buscarLibro(criteriosBusqueda): List<Libro>
  + solicitarPrestamo(libro): Prestamo
  + renovarPrestamo(prestamo): void
}

class Libro {
  - titulo: String
  - autor: String
  - categoria: String
  - isbn: String
  - anyoPublicacion: int
  - idioma: String
  - disponible: boolean
}

class Prestamo {
  - fechaPrestamo: Date
  - fechaVencimiento: Date
  - estado: EstadoPrestamo
  - libro: Libro
  - usuario: Usuario
  + calcularMulta(): float 
}

enum EstadoPrestamo {
  ACTIVO
  RENOVADO
  DEVUELTO
  ATRASADO
}

class SistemaGestionBiblioteca {
  - usuarios: List<Usuario>
  - libros: List<Libro>
  - prestamos: List<Prestamo>

  + registrarUsuario(usuario): void
  + eliminarUsuario(usuario): void
  + buscarLibros(criteriosBusqueda): List<Libro>
  + agregarLibro(libro): void
  + eliminarLibro(libro): void
  + solicitarPrestamo(usuario, libro): Prestamo
  + renovarPrestamo(prestamo): void
  + devolverPrestamo(prestamo): void
  + gestionarInventario(): void
  + generarInformes(): void
}

class Bibliotecario {
  - sistema: SistemaGestionBiblioteca
  + agregarLibro(libro): void
  + eliminarLibro(libro): void
  + gestionarUsuarios(): void
  + generarInformes(): void
}

Usuario  o--  SistemaGestionBiblioteca 
Libro  o--  SistemaGestionBiblioteca 
Prestamo  o--  SistemaGestionBiblioteca 
Usuario  --  Prestamo 
Bibliotecario  --  SistemaGestionBiblioteca 

@enduml
